Hopping and wriggling about. You look as anxious as I feel. #name:Mrs. Crow
If Mr. Crow thinks he should handle this alone, he’s got another thing coming…
I’d bet a pretty fingerbone that the other passengers are frightened. I had better check on them before I go rushing back to the engine.